[package]
name = "johnfig"
version = "0.1.0"
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
thiserror = "1"
serde = { version = "1", default-features = false, features = [ "derive" ] }
serde_json = { version = "1" }
async-fs = "1"
log = "0.4"
futures = { version = "0.3" }
blocking = "1"
tinytemplate = "1"
pathutils = { git = "https://github.com/kildevaeld/pathutils-rs" }
ordered-float = "2"

serde_yaml = { version = "0.8", optional = true }
ron = { version = "0.7", optional = true }
toml = { version = "0.5", optional = true }


[dev-dependencies]
smol = "1"
pretty_env_logger = "0.4"

[features]
default = [ "yaml" ]
yaml = [ "serde_yaml" ]