[package]
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]
edition = "2021"
name = "johnfig"
version = "0.1.0"

[dependencies]
async-fs = "1"
async-stream = "0.3"
async-trait = "0.1"
blocking = "1"
futures = {version = "0.3"}
glob = "0.3"
log = "0.4"
serde = {version = "1", default-features = false, features = ["derive"]}
thiserror = "1"
tinytemplate = "1"
value = {git = "https://github.com/kildevaeld/value-rs", features = ["std", "serde"]}

toback = {git = "https://github.com/kildevaeld/toback-rs"}

# Notify
async-broadcast = {version = "0.3", optional = true}
async-lock = {version = "2", optional = true}
brunson = {git = "https://github.com/kildevaeld/runtime-rs", optional = true}
notify = {version = "5.0.0-pre.13", optional = true}

[dev-dependencies]
brunson = {git = "https://github.com/kildevaeld/runtime-rs", features = ["smol"]}
pretty_env_logger = "0.4"
smol = "1"

[features]
default = ["json", "watch"]

watch = ["notify", "async-broadcast", "async-lock", "brunson"]

all_formats = ["toback/full"]

gura = ["toback/gura"]
json = ["toback/json"]
ron = ["toback/ron"]
toml = ["toback/toml"]
yaml = ["toback/yaml"]
