[package]
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]
edition = "2021"
name = "johnfig"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-fs = "1"
async-stream = "0.3"
async-trait = "0.1"
blocking = "1"
futures = {version = "0.3"}
glob = "0.3"
log = "0.4"
ron = {version = "0.7", optional = true}
serde = {version = "1", default-features = false, features = ["derive"]}
serde_json = {version = "1"}
serde_yaml = {version = "0.8", optional = true}
thiserror = "1"
tinytemplate = "1"
toml = {version = "0.5", optional = true}
value = {git = "https://github.com/kildevaeld/value-rs", features = ["std", "serde"]}

async-broadcast = {version = "0.3", optional = true}
async-lock = {version = "2", optional = true}
notify = {version = "5.0.0-pre.13", optional = true}
runtime = {git = "https://github.com/kildevaeld/runtime-rs"}

[dev-dependencies]
pretty_env_logger = "0.4"
runtime = {git = "https://github.com/kildevaeld/runtime-rs", features = ["smol"]}
smol = "1"

[features]
default = []
watch = ["notify", "async-broadcast", "async-lock"]
yaml = ["serde_yaml"]
